### ISSUE TITLE
Add API Authentication to other Endpoints

### ISSUE THREAD

**Issue by FuckingToasters** [Xazin/mybb_api#12]
Hello, i noticed that the API KEY is only required for the authentication.php endpoint however i want to modify it in a way so that the APIKEY is also required for other endpoints but i don't understand, how i'm able to do this.

Would be nice if someone could help me there.

Regards,
FuckingToasters

**Comment by Xazin** [comment]
I saw your PR #13 

If you separate the fix for hidden content into another PR, I will review that seperately.

As for the intention of adding authentication to other endpoints, it needs more work, I left a comment on the PR.
